use magist;

WITH S AS
(
SELECT 
    T.TABLE_NAME, C.COLUMN_NAME as column_n, C.DATA_TYPE
FROM
    INFORMATION_SCHEMA.TABLES AS T
        JOIN
    INFORMATION_SCHEMA.COLUMNS AS C ON T.TABLE_SCHEMA = C.TABLE_SCHEMA
        AND T.TABLE_NAME = C.TABLE_NAME
WHERE
    T.TABLE_SCHEMA = 'magist'
)
SELECT column_n, count(*) AS count
FROM S
GROUP BY 1
HAVING count > 1
ORDER BY 2 DESC;