SELECT 
    T.TABLE_NAME, C.COLUMN_NAME as column_n, C.DATA_TYPE
FROM
    INFORMATION_SCHEMA.TABLES AS T
        JOIN
    INFORMATION_SCHEMA.COLUMNS AS C ON T.TABLE_SCHEMA = C.TABLE_SCHEMA
        AND T.TABLE_NAME = C.TABLE_NAME
WHERE
    T.TABLE_SCHEMA = 'magist'
    AND REGEXP_LIKE(lower(C.COLUMN_NAME), 'cat|name')
    ;